version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=prakashdb
      - POSTGRES_USER=prakashtcoder
      - POSTGRES_PASSWORD=prakash1234
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
